title: Bombay Earthing House
description: >-
  ISO 9001 certified manufacturer of Copper Bonded Earth Rods, Pipe Electrodes,
  Lightning Arresters, Earth Plates, Cable Trays and earthing accessories. Mumbai, India.
url: "https://bombayearthing.com"
baseurl: ""

markdown: kramdown
permalink: /:title.html

collections:
  products:
    output: true
    permalink: /:path.html

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
